-- Phase 5.2.5 Step F2: add Keel recommendation to mission packets.
--
-- The working group already debates each gap through 4 roles and
-- produces a synthesis. Step F2 extends the debate by one additional
-- substrate call that produces a Keel-voice recommendation (approve
-- / deny / defer) + reasoning, stored here so the morning brief
-- dashboard can display it alongside the raw finding.
--
-- Why here instead of at render time: one short call during the
-- working group run is cheaper than an LLM call on every dashboard
-- page load, and the recommendation has the same full context as
-- the rest of the packet (no risk of drift between the packet's
-- reasoning and the recommendation's reasoning).

ALTER TABLE mission_packets
  ADD COLUMN IF NOT EXISTS keel_recommendation text,
  ADD COLUMN IF NOT EXISTS keel_reasoning text;

COMMENT ON COLUMN mission_packets.keel_recommendation IS
  'Keel-voice recommendation: approve, deny, or defer. Generated by the working group as a final step after role debate + synthesis. Surfaced in the morning brief Preview Branches panel to help [HUMAN] decide quickly.';

COMMENT ON COLUMN mission_packets.keel_reasoning IS
  'Short (2-4 sentence) explanation of why Keel recommends this decision. Context-aware based on the packet finding, proposed_fix, risk_level, and scope_lock results.';
