/**
 * Memory search for Keel.
 *
 * Hybrid search: 70% vector similarity (pgvector) + 30% FTS (tsvector).
 * Falls back to FTS-only if embeddings unavailable.
 * Returns ranked chunks with source file, heading, and relevance score.
 *
 * Vector embeddings generated by Qwen3-Embedding 8B via vLLM-MLX (port 8000).
 * Hybrid search via Supabase RPC (hybrid_memory_search function).
 */

const { execSync, spawnSync } = require('child_process');
const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const { loadEnv } = require('./shared.ts');
const { withTimeout } = require('./utils.ts');

const KEEL_DIR = path.resolve(__dirname, '../..');
const MEMORY_DIR = path.join(KEEL_DIR, 'memory');

interface SearchResult {
  source_file: string;
  heading: string | null;
  content: string;
  file_type: string;
  file_date: string | null;
  decayedRank?: number;
}

interface SearchOptions {
  fileTypes?: string[];
  limit?: number;
  since?: string;
  sourceFile?: string;
}

// --- Query Expansion ---
const STOP_WORDS = new Set([
  'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
  'should', 'may', 'might', 'can', 'shall', 'to', 'of', 'in', 'for',
  'on', 'with', 'at', 'by', 'from', 'as', 'into', 'about', 'between',
  'through', 'during', 'before', 'after', 'above', 'below', 'and', 'but',
  'or', 'not', 'no', 'so', 'if', 'then', 'than', 'that', 'this', 'these',
  'those', 'it', 'its', 'i', 'me', 'my', 'we', 'our', 'you', 'your',
  'he', 'she', 'they', 'them', 'his', 'her', 'what', 'which', 'who',
  'when', 'where', 'how', 'why', 'all', 'each', 'every', 'both', 'some',
  'any', 'most', 'just', 'also', 'very', 'really', 'thing', 'things',
  'stuff', 'something', 'anything', 'everything', 'nothing', 'here',
  'there', 'now', 'then', 'today', 'yesterday', 'recently', 'already',
]);

function expandQuery(text: string): string[] {
  const words = text.trim().split(/\s+/)
    .map(w => w.replace(/[^a-zA-Z0-9]/g, '').toLowerCase())
    .filter(w => w.length > 1 && !STOP_WORDS.has(w));
  return words.length > 0 ? words : text.trim().split(/\s+/).map(w => w.replace(/[^a-zA-Z0-9]/g, '')).filter(w => w.length > 0);
}

/**
 * Local fallback search when Supabase is unavailable.
 */
function searchMemoryLocal(query: string, { limit = 10 }: { limit?: number } = {}): SearchResult[] {
  try {
    if (!query || !query.trim()) return [];
    if (!fs.existsSync(MEMORY_DIR)) return [];

    const keywords = expandQuery(query);
    if (keywords.length === 0) return [];

    const pattern = keywords[0];
    const grepResult = spawnSync('grep', ['-ril', pattern, MEMORY_DIR], {
      timeout: 5000, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe']
    });
    const raw = (grepResult.stdout || '').trim();

    if (!raw) return [];
    const files = raw.split('\n').filter(Boolean).slice(0, limit);

    return files.map((filePath: string) => {
      const relPath = path.relative(KEEL_DIR, filePath);
      const dateMatch = relPath.match(/(\d{4}-\d{2}-\d{2})/);
      let fileType = 'memory';
      if (relPath.includes('daily/')) fileType = 'daily';
      else if (relPath.includes('synthesis/')) fileType = 'synthesis';
      else if (relPath.includes('BUILD_LOG')) fileType = 'build_log';

      let content = '';
      try {
        content = fs.readFileSync(filePath, 'utf8').slice(0, 500);
      } catch { /* best effort */ }

      return {
        source_file: relPath,
        heading: null,
        content,
        file_type: fileType,
        file_date: dateMatch ? dateMatch[1] : null,
      };
    });
  } catch (err) {
    return [];
  }
}

/**
 * Search memory chunks — hybrid first (70% vector + 30% FTS), falls back to FTS-only.
 * All callers get semantic search automatically when embeddings are available.
 */
async function searchMemory(query: string, { fileTypes, limit = 10, since, sourceFile }: SearchOptions = {}): Promise<SearchResult[]> {
  // Try hybrid search first (vector + FTS)
  if (!sourceFile) {
    try {
      const hybridResults = await searchMemoryHybrid(query, { fileTypes, limit, since });
      if (hybridResults.length > 0) return hybridResults;
    } catch { /* hybrid unavailable — fall through to FTS */ }
  }

  // FTS fallback
  const env = loadEnv();
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_SERVICE_KEY;

  if (!url || !key) return searchMemoryLocal(query, { limit });
  if (!query || query.trim().length === 0) return [];

  const keywords = expandQuery(query);
  const tsquery = keywords.join(' & ');

  if (!tsquery) return [];

  const params = new URLSearchParams();
  params.set('select', 'source_file,heading,content,file_type,file_date');
  params.set('content_tsv', `fts.${tsquery}`);
  params.set('order', 'file_date.desc.nullslast');
  params.set('limit', String(limit));

  if (fileTypes && fileTypes.length > 0) {
    params.set('file_type', fileTypes.length === 1
      ? `eq.${fileTypes[0]}`
      : `in.(${fileTypes.join(',')})`
    );
  }

  if (since) {
    params.set('file_date', `gte.${since}`);
  }

  if (sourceFile) {
    params.set('source_file', `eq.${sourceFile}`);
  }

  // Temporal decay: recent memories rank higher.
  const HALF_LIFE_DAYS = 30;
  const LAMBDA = Math.LN2 / HALF_LIFE_DAYS;

  function applyTemporalDecay(rows: SearchResult[]): SearchResult[] {
    const now = Date.now();
    return rows.map(r => {
      let decay = 1.0;
      if (r.file_date) {
        const ageMs = now - new Date(r.file_date).getTime();
        const ageDays = Math.max(0, ageMs / 86400000);
        decay = Math.exp(-LAMBDA * ageDays);
      }
      return { ...r, decayedRank: decay };
    }).sort((a, b) => (b.decayedRank || 0) - (a.decayedRank || 0));
  }

  const rawPromise = new Promise<SearchResult[]>((resolve, reject) => {
    const fullUrl = new URL(`${url}/rest/v1/memory_chunks?${params.toString()}`);

    const req = https.request(fullUrl, {
      method: 'GET',
      headers: {
        'apikey': key,
        'Authorization': `Bearer ${key}`,
        'Content-Type': 'application/json',
      },
    }, (res: any) => {
      let data = '';
      res.on('data', (chunk: string) => data += chunk);
      res.on('end', () => {
        if (res.statusCode >= 400) {
          reject(new Error(`Search failed (${res.statusCode}): ${data.slice(0, 200)}`));
          return;
        }
        try {
          const rows = JSON.parse(data);
          const mapped: SearchResult[] = rows.map((r: any) => ({
            source_file: r.source_file,
            heading: r.heading,
            content: r.content,
            file_type: r.file_type,
            file_date: r.file_date,
          }));
          resolve(applyTemporalDecay(mapped));
        } catch (e) {
          reject(new Error('Failed to parse search results'));
        }
      });
    });

    req.on('error', reject);
    req.end();
  });

  try {
    return await withTimeout(rawPromise, 10000);
  } catch (err) {
    return searchMemoryLocal(query, { limit });
  }
}

/**
 * Hybrid search using pgvector embeddings + FTS.
 * Requires: migration 062 applied, embeddings generated.
 * Falls back to FTS-only searchMemory if embedding generation fails.
 */
async function searchMemoryHybrid(query: string, opts: SearchOptions = {}): Promise<SearchResult[]> {
  const env = loadEnv();
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_SERVICE_KEY;
  const localHost = process.env.LOCAL_HOST || process.env.OMLX_HOST || 'http://localhost:8000';

  if (!url || !key) return searchMemoryLocal(query, { limit: opts.limit });
  if (!query || query.trim().length === 0) return [];

  // Generate query embedding via local inference
  let queryEmbedding: number[];
  try {
    const embResponse = await new Promise<any>((resolve, reject) => {
      const body = JSON.stringify({
        model: process.env.EMBEDDING_MODEL || 'mlx-community/Qwen3-Embedding-8B-4bit-DWQ',
        input: query.slice(0, 8192),
      });
      const embUrl = new URL(`${localHost}/v1/embeddings`);
      const req = http.request(embUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      }, (res: any) => {
        let data = '';
        res.on('data', (chunk: string) => data += chunk);
        res.on('end', () => {
          if (res.statusCode >= 400) { reject(new Error(`Embedding ${res.statusCode}`)); return; }
          try { resolve(JSON.parse(data)); } catch (e: any) { reject(e); }
        });
      });
      req.setTimeout(15000, () => { req.destroy(new Error('Embedding timeout')); });
      req.on('error', reject);
      req.write(body);
      req.end();
    });

    queryEmbedding = embResponse.data?.[0]?.embedding || embResponse.embedding;
    if (!queryEmbedding || !Array.isArray(queryEmbedding)) {
      throw new Error('No embedding returned');
    }
    // Matryoshka truncation: DB uses 1024-dim index, so truncate query to match
    if (queryEmbedding.length > 1024) {
      queryEmbedding = queryEmbedding.slice(0, 1024);
    }
  } catch (embErr) {
    // Embedding failed — throw so searchMemory's catch falls through to FTS
    // (returning searchMemory() here caused infinite recursion: searchMemory → hybrid → searchMemory → hybrid → ...)
    throw embErr;
  }

  // Call hybrid search RPC
  const rpcBody = JSON.stringify({
    query_embedding: JSON.stringify(queryEmbedding),
    query_text: query,
    match_count: opts.limit || 10,
    file_type_filter: opts.fileTypes?.[0] || null,
    since_date: opts.since || null,
  });

  const HALF_LIFE_DAYS = 30;
  const LAMBDA = Math.LN2 / HALF_LIFE_DAYS;

  try {
    const result = await withTimeout(new Promise<SearchResult[]>((resolve, reject) => {
      const rpcUrl = new URL(`${url}/rest/v1/rpc/hybrid_memory_search`);
      const req = https.request(rpcUrl, {
        method: 'POST',
        headers: {
          'apikey': key,
          'Authorization': `Bearer ${key}`,
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(rpcBody),
        },
      }, (res: any) => {
        let data = '';
        res.on('data', (chunk: string) => data += chunk);
        res.on('end', () => {
          if (res.statusCode >= 400) {
            reject(new Error(`Hybrid search ${res.statusCode}: ${data.slice(0, 200)}`));
            return;
          }
          try {
            const rows = JSON.parse(data);
            const now = Date.now();
            const mapped: SearchResult[] = rows.map((r: any) => {
              let decay = 1.0;
              if (r.file_date) {
                const ageDays = Math.max(0, (now - new Date(r.file_date).getTime()) / 86400000);
                decay = Math.exp(-LAMBDA * ageDays);
              }
              return {
                source_file: r.source_file,
                heading: r.heading,
                content: r.content,
                file_type: r.file_type,
                file_date: r.file_date,
                decayedRank: (r.hybrid_score || 0) * decay,
              };
            });
            resolve(mapped.sort((a, b) => (b.decayedRank || 0) - (a.decayedRank || 0)));
          } catch (e) {
            reject(new Error('Failed to parse hybrid search results'));
          }
        });
      });
      req.on('error', reject);
      req.write(rpcBody);
      req.end();
    }), 15000);

    return result;
  } catch (rpcErr) {
    // RPC failed — throw so searchMemory's catch falls through to FTS
    // (returning searchMemory() here caused infinite recursion)
    throw rpcErr;
  }
}

module.exports = { searchMemory, searchMemoryLocal, searchMemoryHybrid };

// --- CLI ---
if (require.main === module) {
  const args = process.argv.slice(2);
  const query = args.find((a: string) => !a.startsWith('--'));
  const typeIdx = args.indexOf('--type');
  const limitIdx = args.indexOf('--limit');
  const sinceIdx = args.indexOf('--since');

  const fileTypes = typeIdx >= 0 && args[typeIdx + 1] ? [args[typeIdx + 1]] : undefined;
  const limit = limitIdx >= 0 && args[limitIdx + 1] ? parseInt(args[limitIdx + 1], 10) : 10;
  const since = sinceIdx >= 0 && args[sinceIdx + 1] ? args[sinceIdx + 1] : undefined;

  if (!query) {
    console.error('Usage: node scripts/lib/memory-search.js "query" [--type daily] [--limit 10] [--since 2026-02-15]');
    process.exit(1);
  }

  searchMemory(query, { fileTypes, limit, since })
    .then((results: SearchResult[]) => {
      if (results.length === 0) {
        console.log('No results found.');
        return;
      }
      console.log(`Found ${results.length} result(s):\n`);
      for (const r of results) {
        console.log(`--- ${r.source_file} ${r.heading ? '— ' + r.heading : ''} (${r.file_type}, ${r.file_date || 'no date'}) ---`);
        console.log(r.content.slice(0, 500));
        console.log('');
      }
    })
    .catch((err: any) => {
      console.error('Search failed:', err.message);
      process.exit(1);
    });
}
